version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/etc-nginx:/etc/nginx:cached
      - ~/workspace/wwwroot:/wwwroot:cached
      # - ../php74/sock:/sock:cached
    networks:
      dev: 
        ipv4_address: 172.19.0.2


  php:
    image: registry.cn-qingdao.aliyuncs.com/xfee/php74:1.0
    container_name: php74
    restart: always
    depends_on: 
      - nginx
    volumes:
      - ~/workspace/wwwroot:/wwwroot:cached
      # - ../php74/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:cached
      # - ../php74/sock:/sock:cached
    networks:
        dev: 
          ipv4_address: 172.19.0.10


  mysql:
    image: mysql:5.6
    container_name: mysql56
    # restart: always
    depends_on: 
      - php
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/etc-mysql:/etc/mysql  
      - ../mysql/var-lib-mysql:/var/lib/mysql
    networks:
      dev: 
        ipv4_address: 172.19.0.20

networks:
  dev:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/16
